name: angles
description: Utility library for handling angles in radians, degrees and turns.
homepage: https://github.com/Jim-Eckerlein/dart-angles
version: 2.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0

dev_dependencies:
  test: ^1.16.8
